pipeline {
    agent { label 'Slave1' }
    environment {
                git_url = "https://github.com/jfrogdev/project-examples.git"
                branch = "master"
    }

    stages {
        stage('Pulling the source code') {
            steps {
                git credentialsId: 'github-credentials',branch: "${branch}", url: "${git_url}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
