pipeline {
    agent any

    stages {
        stage('Pulling the source code') {
            steps {
                git url: 'https://github.com/jfrogdev/project-examples.git'
                git branch: master
            }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
